trigger:
  - main

variables:
  tag: '$(Build.BuildId)'
  acrName: 'streamlitonazureacr'
  acrLoginServer: 'streamlitonazureacr.azurecr.io'
  imageName: 'streamlit-azure-app'
  webAppName: 'streamlit-on-azure'
  resourceGroup: 'streamlit-rg'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: DockerBuild
    displayName: Build and Push Image
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: $(acrLoginServer)/$(imageName)
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Push Docker image to ACR
      inputs:
        command: push
        repository: $(acrLoginServer)/$(imageName)
        tags: |
          $(tag)
          latest

- stage: DeployToWebApp
  displayName: Deploy to Azure Web App
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: Deploy to Web App for Containers
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy to Web App
      inputs:
        azureSubscription: 'Azure subscription 1'
        appName: $(webAppName)
        resourceGroupName: $(resourceGroup)
        containers: |
          $(acrLoginServer)/$(imageName):latest
