trigger:
  - main

variables:
  tag: '$(Build.BuildId)'
  acrName: 'streamlitonazureacr'
  acrLoginServer: 'streamlitonazureacr.azurecr.io'
  imageName: 'streamlit-azure-app'
  webAppName: 'streamlit-on-azure'
  resourceGroup: 'streamlit-rg'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: DockerBuild
    displayName: Build and Push Image
    pool:
      vmImage: ubuntu-latest

    steps:
    - checkout: self  # ✅ Checkout repo code

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: 'streamlit-acr-connection'  # Must match ACR service connection name in Azure DevOps

    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: '$(imageName)'  # Only repo name
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Push Docker image to ACR
      inputs:
        command: push
        repository: '$(imageName)'  # Only repo name
        tags: |
          $(tag)
          latest

    - task: AzureCLI@2
      displayName: Configure Web App to Use Docker Image
      inputs:
        azureSubscription: 'streamlit-rg-connection'  # Replace with your Azure service connection name
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az webapp config container set \
            --name $(webAppName) \
            --resource-group $(resourceGroup) \
            --container-image-name $(acrLoginServer)/$(imageName):$(tag) \
            --container-registry-url https://$(acrLoginServer)
